export const metadata = {
  title: 'Acceptable Use Policy - X-Maker Pro',
};

export default function AcceptableUsePolicy() {
  return (
    <div className="min-h-screen bg-[#0b0f19] text-gray-300 py-20 px-4">
      <div className="max-w-3xl mx-auto space-y-8">
        <h1 className="text-4xl font-bold text-white mb-8">Acceptable Use Policy (AUP)</h1>
        
        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">1. Overview</h2>
          <p>X-Maker Pro provides AI-powered content generation services. To maintain a safe, trusted, and compliant ecosystem, all users must adhere to this Acceptable Use Policy (AUP). By using our extension and services, you agree not to generate or facilitate the generation of prohibited content.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">2. Prohibited Content & Activities</h2>
          <p>You are strictly prohibited from using X-Maker Pro to generate, promote, or distribute content that includes, but is not limited to, the following:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Spam and Deceptive Practices:</strong> Bulk unsolicited messages, repetitive postings, clickbait, phishing, or deceptive promotions.</li>
            <li><strong>Harassment and Hate Speech:</strong> Content that attacks, harasses, or promotes discrimination, hatred, or violence against individuals or groups based on race, ethnicity, religion, gender, sexual orientation, disability, or nationality.</li>
            <li><strong>Impersonation & Misinformation:</strong> Content intended to impersonate real persons, entities, or brands without authorization, or generating false information designed to mislead the public.</li>
            <li><strong>Illegal Activities:</strong> Content promoting, facilitating, or encouraging illegal acts, intellectual property violations, or copyright infringement.</li>
            <li><strong>Malicious Content:</strong> Generation of malicious code, virus-hosting links, or exploits.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">3. Enforcement & Consequences</h2>
          <p>We actively monitor our system usage and webhook records. If we detect or receive reports of violations of this AUP, we reserve the right to enforce compliance through the following actions:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Warning:</strong> Issue a formal warning regarding the violation.</li>
            <li><strong>Service Restriction:</strong> Limit or throttle API access for the associated license key.</li>
            <li><strong>License Revocation & Permanent Ban:</strong> Terminate access permanently by blacklisting the associated License Key (Order ID) in our database. <strong>No refunds will be provided for banned licenses.</strong></li>
            <li><strong>Legal Action:</strong> We reserve the right to report illegal activities to law enforcement and pursue civil legal remedies.</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold text-white">4. Contact & Reporting</h2>
          <p>If you encounter content generated by our tool that violates this AUP, or have questions regarding these rules, please contact our support team immediately.</p>
        </section>
      </div>
    </div>
  );
}
